routes/web.php
			Route::get('check/{id}', 'TaskController@check');
			Route::any('complete',	'TaskController@complete');
			Route::get('add',        'TaskController@add');
			Route::post('save',      'TaskController@save');
			Route::post('update',      'TaskController@update');
			Route::get('buyer-task/{task_id}',   'TaskController@buyerTask');
			Route::get('del/{id}',   'TaskController@del');

			// 导出
			Route::get('export','TaskController@taskExport');

			// 回复任务
			Route::any('reply', 'TaskController@reply');

			Route::get('trash',		      'TaskController@trash');
			Route::get('restore',		  'TaskController@restore');

			Route::get('/','TaskController@index');
		});


		Route::resource('admins',     'AdminController');
		Route::resource('users',      'UserController');
		Route::resource('roles',      'RoleController');
		Route::resource('menus',      'MenuController');
		Route::resource('depart',     'DepartController');
		Route::resource('services',   'ServiceController');
		Route::resource('articles',   'ArticleController');
		Route::resource('message',    'MessageController');
		Route::any('message/reply',  'MessageController@reply');
		Route::get('yijian',	  'MessageController@yijian');
		Route::resource('emergency',   'EmergencyController');
		Route::get('menus/permission/{menu_id}', 'MenuController@menuPermission');
		Route::resource('permissions', 'PermissionController');
		Route::resource('category',   'CategoryController');
		Route::resource('system','SystemController');
		//智能导诊-症状管理
		Route::resource('symptom','SymptomController');
		Route::post('symptom/bath-del','SymptomController@bathDel');
		//智能导诊-疾病管理
        Route::resource('disease','DiseaseController');
        Route::post('disease/bath-del','DiseaseController@bathDel');
//===========智能导诊-身体管理=============
        Route::resource('body','BodyController',['only'=>['index','create','store','edit','update']]);// 身体部位管理
        Route::delete('body/delete','BodyController@delete')->name('body.delete');
        Route::delete('body/deleteAll','BodyController@deleteAll')->name('body.deleteAll');
        Route::get('body/add_symptom/{body}','BodyController@add_symptom')->name('body.add_symptom');
        Route::post('body/add_symptom/store','BodyController@symptom_store')->name('body.add_symptom.store');
// ========================================
        Route::get('disease/symptom/{id}','DiseaseController@dorela');
        Route::post('disease/symptom/insertdata/{id}','DiseaseController@insertdata');
//=======智能导诊---科室控制====================================
        Route::resource('department','DepartmentController',['only'=>['index','create','store','edit','update']]);
        Route::resource('tags','TagsController');
        Route::delete('department/delete','DepartmentController@delete');
        Route::get('tags/image_edit/{id}','TagsController@image_edit')->name('tags.image_edit');
        Route::post('tags/image_update/{id}','TagsController@image_update')->name('tags.image_update');

      
        	
        Route::resource('content','ContentController');

        Route::post('disease/search/','DiseaseController@search')->name('disease.search');
        Route::post('disease/tag_search/','DiseaseController@tag_search')->name('disease.tag_search');
        
        Route::resource('doctor','DoctorController');
        Route::delete('doctor.delete','DoctorController@delete')->name('doctor.delete');







//        ---------------------------
		// 工种管理
		Route::resource('worktype',   'WorktypeController');


		// 采购信息
		Route::resource('purchases',  'PurchaseController');

		// 出库
		Route::resource('outstock',  'OutstockController');

		Route::get('fee/change',  'FeeController@change');
		Route::get('fee/del',  'FeeController@del');
		Route::get('fee/month','FeeController@month');
		Route::resource('fee',  	'FeeController');
		Route::resource('feetype',  'FeetypeController');
		Route::resource('yezhu',    'YezhuController');

		Route::get('outstock/del-goods/{id}','OutstockController@delGoods');
		Route::post('outstock/save-goods','OutstockController@saveGoods');
		Route::post('outstock/update-goods','OutstockController@updateGoods');
		Route::get('outstock/print/{id}',  'OutstockController@print');

		Route::resource('goods',     'GoodsController');
		Route::post('goods/bath-del','GoodsController@bathDel');
		Route::post('goods/import',  'GoodsController@import');
		Route::resource('goodscates','GoodsCateController');
		Route::resource('goodslogs', 'GoodsLogController');

		Route::prefix('wechat')->group(function(){
			Route::get('wxuser/pull',  'WxuserController@pull');
			Route::get('wxuser/import',  'WxuserController@import');
			Route::post('wxuser/save-user','WxuserController@saveToUser');
			Route::resource('wxuser',  'WxuserController');



			Route::get('msgtpl',     'MsgtplController@index');
			Route::get('msgtpl-show/{tpl_key}','MsgtplController@show');
			Route::get('msgtpl-edit/{tpl_key}','MsgtplController@edit');
			Route::post('msgtpl-save',         'MsgtplController@save');
			Route::get('msgtpl-del/{tpl_key}', 'MsgtplController@del');
			Route::get('msgtpl-import','MsgtplController@import');
			Route::get('msgtpl-all','MsgtplController@all');
			Route::get('menu','WxMenuController@index');

			// 素材管理
			Route::any('get-material','WxMaterialController@getMaterial');

			Route::get('material-downvideo','WxMaterialController@downVideo');

			// 发送消息到个人
			Route::any('send-msg','WxMsgController@sendMsg');
		});





		// 统计报表
		Route::prefix('census')->group(function(){
			Route::any('worker-count','CensusController@workerCount');
			Route::any('worker-count-export','CensusController@workerCountExport');
		});

		// 服务信息
		Route::resource('notice','NoticeController');
		Route::resource('worklog','WorklogController');
		Route::resource('worker','WorkerController');


		//退单
		Route::post('refund','IndexController@refund');

		//派工
		Route::post('process','IndexController@process');

		// 补传完工图
		Route::post('process-pic','TaskController@processPic');

		Route::prefix('diancan')->group(function(){
			Route::resource('notice', 'DiancanNoticeController');
			Route::post('notice/update', 'DiancanNoticeController@update');
			Route::resource('shops', 'DiancanShopController');
			Route::resource('users', 'DiancanUserController');
			Route::get('products/repeat/{id}', 'DiancanProductController@repeat');
			Route::resource('products', 'DiancanProductController');
			Route::resource('orders','DiancanOrderController');
			Route::get('order-export','DiancanOrderController@orderExport');
			Route::resource('cates','DiancanProductCateController');
			Route::resource('shopusers','DiancanShopUserController');
			Route::resource('types','DiancanTypeController');

		});
		Route::get('diancan-orders','DiancanOrderController@index');

		//后台首页
		Route::get('/',		   'IndexController@index');

	});

		Route::get('login',    'LoginController@login');
		Route::post('logindo', 'LoginController@loginDo');
		Route::get('logout',   'LoginController@logOut');




});

// 公开的
Route::get('diancan-orders','DiancanOrderController@index');
Route::get('task-list',   'Admin\TaskPublicController@index');

/**
 * 导诊
 */
Route::prefix('daozhen')->namespace('Dz')->group(function(){

	//智能导诊-症状管理
	Route::resource('symptom','SymptomController');
	Route::post('symptom/bath-del','SymptomController@bathDel');
		//智能导诊-疾病管理
    Route::resource('disease','DiseaseController');
    Route::post('disease/bath-del','DiseaseController@bathDel');
	
	//===========智能导诊-身体管理=============
    Route::delete('body/delete','BodyController@delete');
    Route::delete('body/deleteAll','BodyController@deleteAll');
    Route::resource('body','BodyController');
        
    Route::get('body/add_symptom/{body}','BodyController@add_symptom');
    Route::post('body/add_symptom/store','BodyController@symptom_store');
// ========================================
    Route::get('disease/symptom/{id}','DiseaseController@dorela');
    Route::post('disease/symptom/insertdata/{id}','DiseaseController@insertdata');
//=======智能导诊---科室控制====================================
    Route::resource('department','DepartmentController');
    Route::resource('tags','TagsController');
    Route::delete('department/delete','DepartmentController@delete');

   
    Route::get('tags/image_edit/{id}','TagsController@image_edit');
    Route::post('tags/image_update/{id}','TagsController@image_update');
    Route::prefix('content')->group(function(){
    	Route::get('','ContentController@index');
    	Route::get('edit/{id}','ContentController@edit');
    	Route::post('update/{id}','ContentController@update');
    	Route::post('save','ContentController@store');
    	Route::get('image_edit/{id}','ContentController@image_edit');
    	Route::post('image_update/{id}','ContentController@image_update');
    	Route::post('status','ContentController@content_status');
    	Route::get('create','ContentController@create');
    	Route::delete('delete/{id}','ContentController@destroy');
    });
    
    Route::post('disease/search/','DiseaseController@search');
    Route::post('disease/tag_search/','DiseaseController@tag_search');
    
    Route::resource('doctor','DoctorController');
    Route::delete('doctor.delete','DoctorController@delete')->name('doctor.delete');


	// 登录
	Route::get('login','IndexController@login');
	Route::post('login-do','IndexController@loginDo');
	Route::get('log-out','IndexController@logOut');

	//智能导诊-门诊管理
	Route::resource('outpatient','OutpatientController');
    Route::delete('outpatient.delete','OutpatientController@delete')->name('outpatient.delete');
    //智能导诊-就医指南
    Route::resource('question','QuestionController');
    Route::delete('question.delete','QuestionController@delete')->name('question.delete');
    //智能导诊-问题解答
    Route::resource('answer','AnswerController');

    // 首页富文本
    Route::resource('home-info','HomeInfoController');

app/Http/Controllers/Admin/DaozhenController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Models\User;
use App\Http\Controllers\Controller;

class DaozhenController extends Controller
{
    public function login()
    {
         //dd(md5(trim('222222').'111111'));
    	return view('daozhen.login');
    }

    public function loginDo(Request $request)
    {    	
        
        $username  = $request->username;
    	$password = $request->password;

        if(str_contains($request->username, '@')){
            $where['email'] = $username;    
        } else {
            $where['username']  = $username;
        }
        
    	$user = User::where($where)->first();
        
        //dd($where,$user,md5($password.$user->salt),$user->password);
    	if($user) {
            
    		if(md5($password.$user->salt) == $user->password) {
    			$request->session()->put('admin', $user);                
                return redirect('zadmin/daozhen');
    		}else{
    		  return redirect('zadmin/daozhen/login')->with('rs','密码错误');	
    		}
    	}
        return redirect('zadmin/daozhen/login')->with('rs','用户不存在');

    }

    public function logOut(Request $request)
    {
        $request->session()->forget('admin');
        return redirect('zadmin/daozhen/login');
    }

    public function index()
    {
        $content = \DB::table('kf_content')->get()->all();
        $status = \DB::table('kf_content_status')->get()->pluck('status','cid');
        return view('daozhen.index',compact('content','status'));
    }



    public function body()
    {
        return view('daozhen.body');
    }


    public function bodyList(Request $request,kfBody $body)
    {
        $data = \DB::select('SELECT * FROM kf_bodys WHERE (id = ? OR pid = ?) AND (sex = ? OR sex = ?)',[$request->bodyid,$request->bodyid,$request->sex,0]);
        $son = $body->with('symptom')->find($data[0]->id)->symptom->pluck('name','id');
        return view('daozhen.bodyList',compact('data','son'));
    }

    public function symptom(Request $request)
    {
        if(!$request->symptom_name){
            return redirect(route('daozhen.index'));
        }
        return view('daozhen.symptom');
    }

    public  function diseaseRetrieve(Request $request)
    {

        return view('daozhen.diseaseRetrieve');
    }


    public function search(Request $request)
    {
        if(!$request->symptom_name){
            return redirect(route('daozhen.index'));
        }
        return view('daozhen.search');
    }

    /**
     *  科室对应医生
     */
    public function doctor(Request $request)
    {
        $department = Kfdepartment::get();
        $doctor = $department[0]->doctor->pluck('name','id');
        return view('daozhen.doctor',compact('department','doctor'));
    }

    public function doctor_show(Kfdoctor $doctor)
    {
        return view('daozhen.doctor_show',compact('doctor'));
    }

    
}

app/Http/Controllers/Dz/HomeInfoController.php
<?php

namespace App\Http\Controllers\Dz;

use App\Helpers\ImageUploadHandlers;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;


use App\Models\DaozhenHomeInfo;
use DB;

class HomeInfoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $where = [];
        if($request->keyword) {
           
        }
        $list = DaozhenHomeInfo::where($where)->orderBy('id','desc')->paginate(20);
        
        return view('daozhen.home-info.index',compact('list'));
    }


    public function create(Request $request)
    {
       
       
        return view('daozhen.home-info.add');
    }

    public function store(Request $request)
    {
        $data = $request->except('_token');
        
        

        $kc = DaozhenHomeInfo::create($data);
       
        $rs['status'] = 'success';
        $rs['msg']    = '操作成功';
        return redirect('daozhen/home-info')->with('rs',$rs);
    }


    public function edit($id)
    {
        $data = DaozhenHomeInfo::find($id);
       
        return view('daozhen.home-info.edit',compact('data'));
    }

    /**
     * @param Request $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, $id)
    {
        $data = $request->except('_token','_method');
      
        DaozhenHomeInfo::where('id',$id)->update($data);

        $rs['status'] = 'success';
        $rs['msg']    = '操作成功';
        return redirect('daozhen/home-info')->with('rs',$rs);
    }


    


    

    public function destroy($id)
    {   
      
        DaozhenHomeInfo::destroy($id);
        return back();
    }

}

app/Http/Controllers/Wx/Dz/HomeInfoController.php
<?php

namespace App\Http\Controllers\Wx\Dz;


use App\Models\DaozhenHomeInfo;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use DB;

class HomeInfoController extends Controller
{
    
   
    

    /**
     * 文章详情
     */
    public function show(Request $request)
    {
        $rs['status'] = true;
        $where['status'] = 1;
        if($request->id) {
            $where['id'] = (int)$request->id;
        }
        $data = DaozhenHomeInfo::where($where)->first();
        $rs['data'] = $data;
        return response()->json($rs);
    }


    


}

resources/views/daozhen/home-info/add.blade.php
@extends('daozhen.layouts.app')
@include('vendor.ueditor.assets')
@section('css')
    <link href="{{asset('admin/plugins/select2/css/select2.css')}}" rel="stylesheet">
@endsection
@section('content')


    <!-- Page-Title -->
    <div class="row">
        <div class="col-sm-12">
            <h4 class="page-title">内容管理</h4>
            <ol class="breadcrumb">
                <li><a href="{{url('daozhen/')}}">系统</a></li>
                <li><a href="{{ url('daozhen/home-info') }}">内容列表</a></li>
                <li class="active">添加内容</li>
            </ol>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="card-box">
                <h2 class="m-t-0 header-title">添加内容</h2>
                <hr/>
                @if(session('rs'))
                    <div class="alert alert-{{session('rs')['status']}}">
                        {{ session('rs')['msg'] }}
                    </div>
                @endif
                <div class="row">
                    <div class="col-md-9">
                        <form class="form-horizontal" role="form" action="{{ url('daozhen/home-info') }}" method="post" enctype="multipart/form-data">


                <div class="form-group">
                    <label class="col-md-2 control-label">标题</label>
                    <div class="col-md-10">
                        <input type="text" class="form-control" name="title" value="">
                    </div>
                </div>

               
  
<div class="form-group">
                  <label class="col-md-2 control-label">内容</label>
                  <div class="col-md-10">

                            <script type="text/javascript">
                                var ue = UE.getEditor('container');
                                ue.ready(function() {
                                    ue.execCommand('serverparam', '_token', '{{ csrf_token() }}'); // 设置 CSRF token.
                                });
                            </script>
                            <!-- 编辑器容器 -->
                            <script id="container" name="contents" type="text/plain"></script>
</div>
</div>

<div class="form-group">
                  <label class="col-md-2 control-label">状态</label>
                  <div class="col-md-10">
            <input type="radio" name="status" value="1"  checked="">开启
                      <input type="radio" name="status" value="0" >
                      关闭
                  </div>
              </div>

           



                            {{csrf_field()}}
                            <div class="form-group text-center col-md-12">
                                <button type="submit" class="btn btn-info waves-effect waves-light">保存</button>
                            </div>
                        </form>

                    </div>

                </div>
            </div>

        </div> <!-- end col -->


    </div>
@endsection






@section('modal')
   
   
@endsection







@section('js')
<script type="text/javascript" src="{{asset('admin/plugins/select2/js/select2.min.js')}}"></script>
    <script type="text/javascript">

            $('#department_ids').select2(); 
    </script>
@endsection

resources/views/daozhen/home-info/edit.blade.php
@extends('daozhen.layouts.app')
@include('vendor.ueditor.assets')
@section('css')
    <link href="{{asset('admin/plugins/select2/css/select2.css')}}" rel="stylesheet">
@endsection
@section('content')


    <!-- Page-Title -->
    <div class="row">
        <div class="col-sm-12">
            <h4 class="page-title">首页富文本管理</h4>
            <ol class="breadcrumb">
                <li><a href="{{url('daozhen/')}}">系统</a></li>
                <li><a href="{{ url('daozhen/home-info') }}">首页富文本列表</a></li>
                <li class="active">修改首页富文本</li>
            </ol>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="card-box">
                <h2 class="m-t-0 header-title">修改内容</h2>
                <hr/>
                @if(session('rs'))
                    <div class="alert alert-{{session('rs')['status']}}">
                        {{ session('rs')['msg'] }}
                    </div>
                @endif
                <div class="row">
                    <div class="col-md-9">
                         <form class="form-horizontal" role="form" action="{{url('daozhen/home-info/'.$data->id)}}" method="post" enctype="multipart/form-data">

 {{ method_field('PUT') }}


                <div class="form-group">
                  <label class="col-md-2 control-label">标题</label>
                  <div class="col-md-10">
                      <input type="text" class="form-control" name="title" value="{{$data->title}}">
                  </div>
                </div>

                

               

              
<div class="form-group">
                  <label class="col-md-2 control-label">内容</label>
                  <div class="col-md-10">

                            <script type="text/javascript">
                                var ue = UE.getEditor('container');
                                ue.ready(function() {
                                    ue.execCommand('serverparam', '_token', '{{ csrf_token() }}'); // 设置 CSRF token.
                                });
                            </script>
                            <!-- 编辑器容器 -->
                            <script id="container" name="contents" type="text/plain">{!!  $data->contents  !!}
                            </script>
</div>
</div>

            <div class="form-group">
                  <label class="col-md-2 control-label">状态</label>
                  <div class="col-md-10">
                      <input type="radio" name="status" value="1" {{$data->status==1?'checked':''}}>开启
                      <input type="radio" name="status" value="0" {{$data->status==0?'checked':''}}>
                      关闭
                  </div>
              </div>

                



                            {{csrf_field()}}
                            <div class="form-group text-center col-md-12">
                                <button type="submit" class="btn btn-info waves-effect waves-light">保存</button>
                            </div>
                        </form>

                    </div>

                </div>
            </div>

        </div> <!-- end col -->


    </div>
@endsection






@section('modal')
    
@endsection







@section('js')

    <script type="text/javascript">


    </script>
@endsection
@section('js')
<script type="text/javascript" src="{{asset('admin/plugins/select2/js/select2.min.js')}}"></script>
    <script type="text/javascript">

            $('#department_ids').select2(); 
    </script>
@endsection

resources/views/daozhen/home-info/index.blade.php
@extends('daozhen.layouts.app')
@section('content')

    <!-- Page-Title -->
    <div class="row">
        <div class="col-sm-12">
            <h4 class="page-title">公告管理</h4>
            <ol class="breadcrumb">
                <li><a href="{{url('zadmin/')}}">系统</a></li>

                <li class="active">公告列表</li>
            </ol>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="card-box">

                <div class="row">
                    <div class="col-sm-4">
                        <form role="form" href="{{ route('department.index') }}">
                            <div class="form-group contact-search col-sm-8 m-b-30">
                                <input type="text" id="search" class="form-control"  name="name" value="{{ Request()->name ?? '' }}" placeholder="输入标题搜索">

                            </div>
                            <div class="col-sm-4">
                                <button type="submit" class="btn btn-white"><i class="fa fa-search"></i></button>
                            </div> <!-- form-group -->
                        </form>
                    </div>



                    <div class="col-sm-7">

                       
                            <a href="{{  url('daozhen/home-info/create') }}" class="btn btn-primary btn-md waves-effect waves-light m-b-30"
                            ><i class="md md-add"></i>添加</a>
                       


                    </div>
                </div>
                
                <hr/>
                @if(session('rs'))
                    <div class="alert alert-{{session('rs')['status']}}">
                        {{ session('rs')['msg'] }}
                    </div>
                @endif

                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>标题</th>
                            
                            <th>添加时间</th>
                            <th>开关</th>
                            <th style="width: 200px;">操作</th>
                        </tr>
                        </thead>

                        <tbody>
                        
                            @foreach($list as $k =>$v)
                            <tr>
                                <td>{{$v->id}}</td>
                                <td>
                                    {{$v->title}}
                                </td>
                                
                                
                                <td>
                                   {{$v->created_at}}
                                </td>
                                <td>
                <span class="btn btn-sm btn-{{$v->status==1?'success':'danger'}}">{{$v->status==1?'开启':'关闭'}}</span>  
                            
                                </td>

                                        <td>
    <a href="{{ url('daozhen/home-info/'.$v->id.'/edit') }}" class="btn btn-sm btn-info" >编辑</a>
    <a href="{{url('daozhen/home-info',$v->id)}}" class="btn btn-sm btn-danger" data-method="delete" 
  data-token="{{csrf_token()}}" data-confirm="确定删除吗?">删除</a>
                                           
                                        </td>
                               

                            </tr>
                            @endforeach
                         







                        </tbody>
                    </table>


                </div>
                 {{ $list->links() }}

                </div>

        </div> <!-- end col -->


    </div>

@endsection



@section('modal')
   
@endsection

@section('js')
    <script type="text/javascript">
        $('#checkAll').click(function () {
            $('input:checkbox').prop('checked', this.checked);
        });


        $('.bathDel').on('click',function(){
            var ids = $('.check_class:checked').map(function() {
                return this.value;
            }).get();
            if(ids==''){
                alert('请选择要删除的数据');return;
            }
            var url="{{ route('body.deleteAll') }}";
            var data = {
                'ids':ids,
                '_method':'DELETE',
                '_token' :'{{ csrf_token() }}'
            };
            // data.ids = ids;
            {{--data._token = "{{csrf_token()}}";--}}
            $.post(url,data,function(data){
                // if(data,code == 200) {
                window.location.reload();
                // }
            },'json');
            // console.info(ids);
        });

        function display(id) {
            if($('.son_'+id).attr('hidden') == 'hidden'){
                $('.son_'+id).removeAttr('hidden');
            } else {
                $('.son_'+id).attr('hidden',true);
            }
        }

       


        
    </script>
@endsection