routes/web.php
			Route::get('check/{id}', 'TaskController@check');
			Route::any('complete',	'TaskController@complete');
			Route::get('add',        'TaskController@add');
			Route::post('save',      'TaskController@save');
			Route::post('update',      'TaskController@update');
			Route::get('buyer-task/{task_id}',   'TaskController@buyerTask');
			Route::get('del/{id}',   'TaskController@del');

			// 导出
			Route::get('export','TaskController@taskExport');

			// 回复任务
			Route::any('reply', 'TaskController@reply');

			Route::get('trash',		      'TaskController@trash');
			Route::get('restore',		  'TaskController@restore');

			Route::get('/','TaskController@index');
		});


		Route::resource('admins',     'AdminController');
		Route::resource('users',      'UserController');
		Route::resource('roles',      'RoleController');
		Route::resource('menus',      'MenuController');
		Route::resource('depart',     'DepartController');
		Route::resource('services',   'ServiceController');
		Route::resource('articles',   'ArticleController');
		Route::resource('message',    'MessageController');
		Route::any('message/reply',  'MessageController@reply');
		Route::get('yijian',	  'MessageController@yijian');
		Route::resource('emergency',   'EmergencyController');
		Route::get('menus/permission/{menu_id}', 'MenuController@menuPermission');
		Route::resource('permissions', 'PermissionController');
		Route::resource('category',   'CategoryController');
		Route::resource('system','SystemController');
		//智能导诊-症状管理
		Route::resource('symptom','SymptomController');
		Route::post('symptom/bath-del','SymptomController@bathDel');
		//智能导诊-疾病管理
        Route::resource('disease','DiseaseController');
        Route::post('disease/bath-del','DiseaseController@bathDel');
//===========智能导诊-身体管理=============
        Route::resource('body','BodyController',['only'=>['index','create','store','edit','update']]);// 身体部位管理
        Route::delete('body/delete','BodyController@delete')->name('body.delete');
        Route::delete('body/deleteAll','BodyController@deleteAll')->name('body.deleteAll');
        Route::get('body/add_symptom/{body}','BodyController@add_symptom')->name('body.add_symptom');
        Route::post('body/add_symptom/store','BodyController@symptom_store')->name('body.add_symptom.store');
// ========================================
        Route::get('disease/symptom/{id}','DiseaseController@dorela');
        Route::post('disease/symptom/insertdata/{id}','DiseaseController@insertdata');
//=======智能导诊---科室控制====================================
        Route::resource('department','DepartmentController',['only'=>['index','create','store','edit','update']]);
        Route::resource('tags','TagsController');
        Route::delete('department/delete','DepartmentController@delete');
        Route::get('tags/image_edit/{id}','TagsController@image_edit')->name('tags.image_edit');
        Route::post('tags/image_update/{id}','TagsController@image_update')->name('tags.image_update');

      
        	
        Route::resource('content','ContentController');

        Route::post('disease/search/','DiseaseController@search')->name('disease.search');
        Route::post('disease/tag_search/','DiseaseController@tag_search')->name('disease.tag_search');
        
        Route::resource('doctor','DoctorController');
        Route::delete('doctor.delete','DoctorController@delete')->name('doctor.delete');







//        ---------------------------
		// 工种管理
		Route::resource('worktype',   'WorktypeController');


		// 采购信息
		Route::resource('purchases',  'PurchaseController');

		// 出库
		Route::resource('outstock',  'OutstockController');

		Route::get('fee/change',  'FeeController@change');
		Route::get('fee/del',  'FeeController@del');
		Route::get('fee/month','FeeController@month');
		Route::resource('fee',  	'FeeController');
		Route::resource('feetype',  'FeetypeController');
		Route::resource('yezhu',    'YezhuController');

		Route::get('outstock/del-goods/{id}','OutstockController@delGoods');
		Route::post('outstock/save-goods','OutstockController@saveGoods');
		Route::post('outstock/update-goods','OutstockController@updateGoods');
		Route::get('outstock/print/{id}',  'OutstockController@print');

		Route::resource('goods',     'GoodsController');
		Route::post('goods/bath-del','GoodsController@bathDel');
		Route::post('goods/import',  'GoodsController@import');
		Route::resource('goodscates','GoodsCateController');
		Route::resource('goodslogs', 'GoodsLogController');

		Route::prefix('wechat')->group(function(){
			Route::get('wxuser/pull',  'WxuserController@pull');
			Route::get('wxuser/import',  'WxuserController@import');
			Route::post('wxuser/save-user','WxuserController@saveToUser');
			Route::resource('wxuser',  'WxuserController');



			Route::get('msgtpl',     'MsgtplController@index');
			Route::get('msgtpl-show/{tpl_key}','MsgtplController@show');
			Route::get('msgtpl-edit/{tpl_key}','MsgtplController@edit');
			Route::post('msgtpl-save',         'MsgtplController@save');
			Route::get('msgtpl-del/{tpl_key}', 'MsgtplController@del');
			Route::get('msgtpl-import','MsgtplController@import');
			Route::get('msgtpl-all','MsgtplController@all');
			Route::get('menu','WxMenuController@index');

			// 素材管理
			Route::any('get-material','WxMaterialController@getMaterial');

			Route::get('material-downvideo','WxMaterialController@downVideo');

			// 发送消息到个人
			Route::any('send-msg','WxMsgController@sendMsg');
		});





		// 统计报表
		Route::prefix('census')->group(function(){
			Route::any('worker-count','CensusController@workerCount');
			Route::any('worker-count-export','CensusController@workerCountExport');
		});

		// 服务信息
		Route::resource('notice','NoticeController');
		Route::resource('worklog','WorklogController');
		Route::resource('worker','WorkerController');


		//退单
		Route::post('refund','IndexController@refund');

		//派工
		Route::post('process','IndexController@process');

		// 补传完工图
		Route::post('process-pic','TaskController@processPic');

		Route::prefix('diancan')->group(function(){
			Route::resource('notice', 'DiancanNoticeController');
			Route::post('notice/update', 'DiancanNoticeController@update');
			Route::resource('shops', 'DiancanShopController');
			Route::resource('users', 'DiancanUserController');
			Route::get('products/repeat/{id}', 'DiancanProductController@repeat');
			Route::resource('products', 'DiancanProductController');
			Route::resource('orders','DiancanOrderController');
			Route::get('order-export','DiancanOrderController@orderExport');
			Route::resource('cates','DiancanProductCateController');
			Route::resource('shopusers','DiancanShopUserController');
			Route::resource('types','DiancanTypeController');

		});
		Route::get('diancan-orders','DiancanOrderController@index');

		//后台首页
		Route::get('/',		   'IndexController@index');

	});

		Route::get('login',    'LoginController@login');
		Route::post('logindo', 'LoginController@loginDo');
		Route::get('logout',   'LoginController@logOut');




});

// 公开的
Route::get('diancan-orders','DiancanOrderController@index');
Route::get('task-list',   'Admin\TaskPublicController@index');

/**
 * 导诊
 */
Route::prefix('daozhen')->namespace('Dz')->group(function(){

	//智能导诊-症状管理
	Route::resource('symptom','SymptomController');
	Route::post('symptom/bath-del','SymptomController@bathDel');
		//智能导诊-疾病管理
    Route::resource('disease','DiseaseController');
    Route::post('disease/bath-del','DiseaseController@bathDel');
	
	//===========智能导诊-身体管理=============
    Route::delete('body/delete','BodyController@delete');
    Route::delete('body/deleteAll','BodyController@deleteAll');
    Route::resource('body','BodyController');
        
    Route::get('body/add_symptom/{body}','BodyController@add_symptom');
    Route::post('body/add_symptom/store','BodyController@symptom_store');
// ========================================
    Route::get('disease/symptom/{id}','DiseaseController@dorela');
    Route::post('disease/symptom/insertdata/{id}','DiseaseController@insertdata');
//=======智能导诊---科室控制====================================
    Route::resource('department','DepartmentController');
    Route::resource('tags','TagsController');
    Route::delete('department/delete','DepartmentController@delete');

   
    Route::get('tags/image_edit/{id}','TagsController@image_edit');
    Route::post('tags/image_update/{id}','TagsController@image_update');
    Route::prefix('content')->group(function(){
    	Route::get('','ContentController@index');
    	Route::get('edit/{id}','ContentController@edit');
    	Route::post('update/{id}','ContentController@update');
    	Route::post('save','ContentController@store');
    	Route::get('image_edit/{id}','ContentController@image_edit');
    	Route::post('image_update/{id}','ContentController@image_update');
    	Route::post('status','ContentController@content_status');
    	Route::get('create','ContentController@create');
    	Route::delete('delete/{id}','ContentController@destroy');
    });
    
    Route::post('disease/search/','DiseaseController@search');
    Route::post('disease/tag_search/','DiseaseController@tag_search');
    
    Route::resource('doctor','DoctorController');
    Route::delete('doctor.delete','DoctorController@delete')->name('doctor.delete');


	// 登录
	Route::get('login','IndexController@login');
	Route::post('login-do','IndexController@loginDo');
	Route::get('log-out','IndexController@logOut');

	//智能导诊-门诊管理
	Route::resource('outpatient','OutpatientController');
    Route::delete('outpatient.delete','OutpatientController@delete')->name('outpatient.delete');
    //智能导诊-就医指南
    Route::resource('question','QuestionController');
    Route::delete('question.delete','QuestionController@delete')->name('question.delete');
    //智能导诊-问题解答
    Route::resource('answer','AnswerController');

    // 首页富文本
    Route::resource('home-info','HomeInfoController');

app/Models/Outstock.php
<?php
namespace App\Models;
use DB;

use Illuminate\Database\Eloquent\Model;

class Outstock extends Model
{
    protected $guarded = ['id'];

    public function room()
    {
    	return $this->belongsTo(Room::class);
    }

    public function goods()
    {
    	return $this->hasMany(OutstockGoods::class);
    }

    public function getGoodsNameAttribute()
    {
    	$where['outstock_id'] = $this->id;	
    	$ids = OutstockGoods::where($where)->pluck('goods_id');
    	$names = Goods::whereIn('id',$ids)
    					->pluck('name')->toArray();
    	return implode(',', $names);
    }
}

app/Http/Controllers/Admin/OutstockController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Repos\OutstockRepo;
use App\Repos\GoodsRepo;
use App\Models\Room;
use DB;


class OutstockController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $where = [];
        $list = OutstockRepo::pages($where);
        return view('admin.outstock.index',compact('list'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $goods = GoodsRepo::get();
        $rooms = Room::all();
        return view('admin.outstock.add',compact('rooms','goods'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rs['status'] = 'danger';
        $rs['msg']    = '操作失败';
        $data = $request->except('_token');
        
        $flag   = OutstockRepo::store($data);
        if($flag['status'] == true) {
             $rs['status'] = 'success';
             $rs['msg']    = '操作成功';
            return redirect('zadmin/outstock')->with('rs',$rs);
        }
        $rs['msg'] = $flag['msg'];
        return back()->withInput()->with('rs',$rs);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = OutstockRepo::find(['id'=>$id]);
        $rooms = Room::all();
        $goods = GoodsRepo::get();
        return view('admin.outstock.edit',compact('data','rooms','goods'));
    }

    public function print($id)
    {
        $data = OutstockRepo::find(['id'=>$id]);
        return view('admin.outstock.print',compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $flag = OutstockRepo::destroy($id);
       
            return back();
        
    }

    public function delGoods($id)
    {
        OutstockRepo::delGoods($id);
        return back();
    }

    public function saveGoods(Request $request)
    {
        $data = $request->except('_token');
        //dd($data);
        OutstockRepo::saveGoods($data);
        return back();
    }

    public function updateGoods(Request $request)
    {
        $data = $request->except(['_token']);
        $flag = OutstockRepo::updateGoods($data);
        return back();
    }
}

resources/views/admin/outstock/add.blade.php
@extends('admin.layouts.app')
@section('content')

                        <!-- Page-Title -->
                        <div class="row">
                            <div class="col-sm-12">
                                <h4 class="page-title">出库单管理</h4>
                                <ol class="breadcrumb">
                                    <li><a href="{{url('zadmin/')}}">系统</a></li>
                                    <li><a href="{{url('zadmin/purchases')}}">出库单管理</a></li>
                                    <li class="active">添加出库单</li>
                                </ol>
                            </div>
                        </div>
                        
                        <div class="row">
                        	<div class="col-lg-12">
  <form class="form-horizontal" role="form" action="{{url('zadmin/outstock')}}" method="post" >                          
          <div class="card-box">
                            <h2 class="m-t-0 header-title ">出库单基本信息</h2>
                            <hr/>
                             @if(session('rs'))
                              <div class="alert alert-{{session('rs')['status']}}">
                                {{ session('rs')['msg'] }}
                              </div>
                              @endif
                        			<div class="row">
			                        	<div class="col-md-12">
                                  
                  <div class="form-group col-md-3">
                      <label class="col-md-3 control-label">单号</label>
                      <div class="col-md-9">
                        <input type="text" class="form-control" name="code" required="" value="{{'CK'.date('YmdHis')}}">
                      </div>
                  </div> 
                  <div class="form-group col-md-3">
                      <label class="col-md-3 control-label">科室</label>
                      <div class="col-md-9">
                        <select  class="form-control" name="room_id" required="">
                          <option value="">请选择</option>
                          @foreach($rooms as $s)
                          <option value="{{$s->id}}">{{$s->name}}</option>
                          @endforeach
                        </select>
                      </div>
                  </div>               
                  <div class="form-group col-md-3">
                      <label class="col-md-3 control-label">姓名</label>
                      <div class="col-md-9">
                        <input type="text" class="form-control" name="name" required="" value="">
                      </div>
                  </div>
                  <div class="form-group col-md-3">
                      <label class="col-md-3 control-label">联系</label>
                      <div class="col-md-9">
                        <input type="text" class="form-control" name="phone" required="" value="">
                      </div>
                  </div>

                   <div class="form-group col-md-4">
                      <label class="col-md-4 control-label">出库日期</label>
                      <div class="col-md-8">
                        <input type="text" class="form-control" name="outed_at" required="" value="{{date('Y-m-d')}}">
                      </div>
                  </div>
                                                                                                                 
                  <div class="form-group col-md-8">
                      <label class="col-md-3 control-label">备注</label>
                      <div class="col-md-9">
                         <input type="text" class="form-control" name="remark"  value="">
                              
                      </div>
                  </div>
                                            
                </div>			                        	
			     </div>
          </div>

    <div class="card-box">
      <div class="pull-left m-t-15">
                            <h2 class="m-t-0 header-title">物品信息</h2>
                          </div>
                         
                           
                            
            <div class="row">
                <div class="col-md-12">
                  <table cellspacing="0" cellpadding="0" border="0" class="table table-striped table-bordered  no-footer" id="car">
                    <thead>
                      <tr>
                      
                      <th class="">配件</th>
                      <th class="">数量</th>
                      <th class="">出库单价</th>
                      
                      <th class="">操作</th>
                    </tr>
                    </thead>
          <tbody class="caritem">
            <tr>            
              
              <td>
                  <select  class="form-control" placeholder="" name="goods_id[]">
                    <option value="">请选择</option>
                    @foreach($goods as $b)
                    <option value="{{$b->id}}">{{$b->name}}</option>
                    @endforeach
                  </select>
              </td>
              <td>
                  <input  class="form-control car-serie"  name="goods_num[]" />
                  
              </td>
              <td>
                <input type="text" class="form-control" placeholder="" name="goods_price[]" value="" />
              </td>
              
              <td width="100">
                  <button type="button" class="btn btn-sm btn-primary btn-add"><i class="md md-add"></i></button>
                  <button type="button" class="btn btn-sm btn-danger btn-remove"><i class="md md-remove"></i></button>
              </td>
            </tr>
          </tbody>
        </table>                  

                                           
      </div>                                
           </div>
          </div>  

          <div class="card-box">
            <div class="row">
              <div class="col-md-6"><button type="submit" class="btn btn-danger">保存</div>
              <div class="col-md-6"></div>
            </div>
          </div>    
          {{csrf_field()}}  

                              </form>   
                            </div> <!-- end col -->

                            
                        </div>
@endsection

@section('modal')        
     <div class="modal fade car-modal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" >
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title" id="myLargeModalLabel">添加车辆</h4>
                </div>
                <div class="modal-body">
                  <form class="form-horizontal" role="form">                                    
                    <div class="form-group">
                      <label class="col-md-2 control-label">车牌号码</label>
                      <div class="col-md-10">
                        <input type="text" class="form-control" value="">
                      </div>
                    </div>
                    <div class="form-group">
                      <label class="col-md-2 control-label" for="example-email">车架号/VIN号</label>
                      <div class="col-md-10">
                        <input type="email" id="example-email" name="example-email" class="form-control" placeholder="Email">
                      </div>
                    </div>
                    <div class="form-group">
                      <label class="col-md-2 control-label">车辆类型</label>
                        <div class="col-md-10">
                          
                        </div>
                    </div>
                                                                       
                    <div class="form-group">
                      <label class="col-md-2 control-label">发动机号</label>
                        <div class="col-md-10">
                        <input type="text" class="form-control" placeholder="">
                        </div>
                    </div>                                                                        
                                           
         </form>                              
                </div>
                                            </div><!-- /.modal-content -->
                                        </div><!-- /.modal-dialog -->
                                    </div><!-- /.modal -->

@endsection
@section('js')
<script type="text/javascript">
  $(document).on('click','.btn-add',function(){
            var tr = $('.caritem tr').eq(0).clone();

            $('#car').append(tr);
            console.info(tr);
        });
       
        $(document).on('click','.btn-remove',function(){
            $(this).parents('tr').remove();
        })
 $('#add-car').on('click',function(){
  $('.car-modal').modal('show');
 }); 
</script>
@endsection

                        
                        
                        

                  
            
   

           



    
        

resources/views/admin/outstock/index.blade.php
@extends('admin.layouts.app')
@section('content')

                        <!-- Page-Title -->
                        <div class="row">
                            <div class="col-sm-12">
                                <h4 class="page-title">出库单管理</h4>
                                <ol class="breadcrumb">
                                    <li><a href="{{url('zadmin/')}}">系统</a></li>
                                   
                                    <li class="active">出库单列表</li>
                                </ol>
                            </div>
                        </div>
                        
                        <div class="row">
                        	<div class="col-lg-12">
                        		<div class="card-box">
                        			<div class="row">
			                        	<div class="col-sm-8">
			     <form role="form">
			         <div class="form-group contact-search m-b-30 col-sm-8">
			           <input type="text" id="search" name="keyword" class="form-control" placeholder="输入姓名/联系">
			             
			         </div>
               <div class="col-sm-4"><button type="submit" class="btn btn-white"><i class="fa fa-search"></i></button></div> <!-- form-group -->
			     </form>
			                        	</div>
			                        	<div class="col-sm-4">
			                        		

                                  <a href="{{url('zadmin/outstock/create')}}" class="btn btn-primary btn-md waves-effect waves-light m-b-30"  
                                  ><i class="md md-add"></i>添加</a>
			                        	</div>
			                        </div>

                              @if(session('rs'))
                              <div class="alert alert-{{session('rs')['status']}}">
                                {{ session('rs')['msg'] }}
                              </div>
                              @endif
			                        
                        			<div class="table-responsive">
                                        <table class="table table-hover">
                                        	<thead>
												<tr>
													<th style="min-width: 35px;">
													ID
                                                        
													</th>
													<th>单号</th>
                          <th>配件</th>
													<th>姓名</th>
                          <th>联系</th>
                          <th>科室</th>
                          <th>出库日期</th>
                          <th>备注</th>
                          
                         
													<th style="width: 200px;">操作</th>
												</tr>
											</thead>
											
                      <tbody>

                      @foreach($list as $v)
                          <tr>
                              <td>
                                  {{$v->id}}
                                                        
                                                      
                              </td>
                                                    
                  <td>
                      {{$v->code}}
                  </td>
                  <td>{{$v->goods_name}}</td>
                  <td>{{$v->name}}</td>
                  <td>
                      {{$v->phone}}
                  </td>
                  <td>
                      {{object_get($v,'room.name')}}
                  </td>
                  <td>{{$v->outed_at}}</td>
                  <td>{{$v->remark}}</td>
                                        
                                                    
                                                    
                                                
                                                    
                                                   
                  <td>
                    <a href="{{url('zadmin/outstock/'.$v->id.'/edit')}}" ><i class="md md-edit"></i>详情</a>
                    <a href="{{url('zadmin/outstock',$v->id)}}" data-method="delete" 
  data-token="{{csrf_token()}}" data-confirm="确定删除吗?"><i class="md md-close"></i>删除</a>
                  </td>
              </tr>
                                            @endforeach    
                                                
                                               
                                               
                                                
                                               
                                                
                                            
                                            </tbody>
                                        </table>
                                    </div>

                                     {{ $list->links() }}
                        		</div>
                                
                            </div> <!-- end col -->

                            
                        </div>
@endsection
                        
                        
                        

                  
            
    @section('modal')        
     
    @endsection        
       

           



    
        
    

resources/views/admin/outstock/print.blade.php
<!DOCTYPE html>
<html>
<head>
  <title></title>
<style type="text/css">
  body{font-family: 宋体;font-size: 14px;}
  .title{font-size: 18px; text-align: center;}
  .m-b-10{clear: both;margin-bottom: 10px;}
  .m-b-15{clear: both;margin-bottom: 15px;}
   table,table tr th, table tr td { border:1px solid #000;text-align: center }
  table{width: 100%;border-collapse: collapse;};
  .textline{font-size: 12px;}

</style>
</head>
<body>
     <h5 class="title">东湖分院 事务处理中心 出库单</h5>
            <p class="textline">
              出库单号:{{$data->code}}&nbsp;&nbsp;&nbsp;提交时间:{{$data->created_at->format('Ymd H:i:s')}}&nbsp;&nbsp;&nbsp; 
              出库时间:{{$data->outed_at}}
            </p>                     
            <table class="m-b-15">
              
                <tr>
                  <td>姓名</td>
                  
                  <td>联系</td>
                  
                  <td>科室</td>
                
                  <td>用途</td>
                 
              
                </tr>
                <tr>
                 
                  <td>{{$data->name}}</td>
                  
                  <td>{{$data->phone}}</td>
                  
                  <td>{{object_get($data,'room.name')}}</td>
                 
                  <td>{{$data->arrived_at}}</td>
              
                </tr>                     
              </table>


              <table class="m-b-10">
                <tr>
                  <th colspan="9">材料清单</th>
                </tr>
                <tr>
                  <td>序号</td>
                   <td>材料名称</td>
                  <td>材料编号</td>
                 

                  <td>单位</td>
                  <td>数量</td>
                  
                  <td>价格</td>
                  
                 
                </tr>
                @foreach($data->goods as $key=>$p)
                <tr>
                  <td>{{$key+1}} </td>
                   <td>{{object_get($p,'goods.name')}}</td>
                  <td>{{object_get($p,'goods.source_code')}}</td>
                 
                  <td>{{object_get($p,'goods.unit')}}</td>
                  <td>{{$p->goods_num}}</td>
                 
                  <td></td>
                  
                  
                </tr>
                @endforeach
              
              </table>

             
              <p class="textline">
                管理员：_________ &nbsp;&nbsp;&nbsp;&nbsp;领取人：_________
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;备注：________
              </p>

          
</body>
</html>

          
                             
           
              
              
            
               

                  
            
        
       

           



    
        
    